/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetLeenaRouteImport } from './routes/meet-leena'
import { Route as PrioritiesRouteImport } from './routes/priorities'
import { Route as WaterRouteImport } from './routes/water'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetLeenaRoute = MeetLeenaRouteImport.update({
  id: '/meet-leena',
  path: '/meet-leena',
  getParentRoute: () => rootRouteImport,
} as any)
const PrioritiesRoute = PrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterRoute = WaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meet-leena': typeof MeetLeenaRoute
  '/priorities': typeof PrioritiesRoute
  '/water': typeof WaterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meet-leena': typeof MeetLeenaRoute
  '/priorities': typeof PrioritiesRoute
  '/water': typeof WaterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meet-leena': typeof MeetLeenaRoute
  '/priorities': typeof PrioritiesRoute
  '/water': typeof WaterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meet-leena' | '/priorities' | '/water'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meet-leena' | '/priorities' | '/water'
  id: '__root__' | '/' | '/meet-leena' | '/priorities' | '/water'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeetLeenaRoute: typeof MeetLeenaRoute
  PrioritiesRoute: typeof PrioritiesRoute
  WaterRoute: typeof WaterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-leena': {
      id: '/meet-leena'
      path: '/meet-leena'
      fullPath: '/meet-leena'
      preLoaderRoute: typeof MeetLeenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priorities': {
      id: '/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof PrioritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water': {
      id: '/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof WaterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeetLeenaRoute: MeetLeenaRoute,
  PrioritiesRoute: PrioritiesRoute,
  WaterRoute: WaterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
